/*
 * $Id: inv.h,v 1.1 2005-08-22 16:07:29 thebjoern Exp $
*/

#define INVENTORY_NONE				0
//ammo
#define INVENTORY_SHELLS			18
#define INVENTORY_BULLETS			19
#define INVENTORY_ROCKETS			23
#define INVENTORY_SLUGS				24
//powerups
#define INVENTORY_REDFLAG			45
#define INVENTORY_BLUEFLAG			46
// MFQ3
#define INVENTORY_FFAR				50
#define INVENTORY_IRONBOMB			51
#define INVENTORY_AUTOCANNON		52
#define INVENTORY_MAINGUN			53
//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_HEALTHSMALL		1
#define MODELINDEX_HEALTH			2
#define MODELINDEX_HEALTHLARGE		3
#define MODELINDEX_HEALTHMEGA		4

#define MODELINDEX_FFAR				5
#define MODELINDEX_IRONBOMB			6
#define MODELINDEX_AUTOCANNON		7
#define MODELINDEX_MAINGUN			8

#define MODELINDEX_SHELLS			9
#define MODELINDEX_BULLETS			10
#define MODELINDEX_ROCKETS			11
#define MODELINDEX_SLUGS			12

#define MODELINDEX_REDFLAG			13
#define MODELINDEX_BLUEFLAG			14

// MFQ3
#define WEAPONINDEX_FFAR				1
#define WEAPONINDEX_IRONBOMB			2
#define WEAPONINDEX_AUTOCANNON			3
#define WEAPONINDEX_MAINGUN				4
